import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { ReactQueryProvider } from './react-query-provider';
import { TuringHeader } from '@/components/turing/header';
import { WalletProvider } from '../components/wallet/wallet-provider';
import { SocketProvider } from '../components/socket/socket-provider';

export const metadata = {
  title: 'turing-tournament',
  description: 'Generated by create-solana-dapp',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SocketProvider>
          <WalletProvider>
            <ReactQueryProvider>
              <ClusterProvider>
                <TuringHeader />
                {children}
              </ClusterProvider>
            </ReactQueryProvider>
          </WalletProvider>
        </SocketProvider>
      </body>
    </html>
  );
}