[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
basic = "DzSv519LBQjx4KHcQ7LLaeHXSq6bkLAYJooN2L42tv9W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"


